### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by virtualdj** [magcode/lametric-tools#1]
Hi, just a question that I don't see on the README. How do these scripts can be installed on a LaMetric device?

**Comment by magcode** [comment]
Hi,

yes. Installation steps are not yet documented.
So far I did not see much interested so I did not invest the time.

Steps are basically:

Open the device
Remove sdcard
clone sdcard
mount the filesystem of the clone
modify the root password
write changes to sdcard
boot with new sdcard

Off course this is way too less information. I'll add more details in case I have some time.

**Comment by virtualdj** [comment]
Mmm, I see, it would be great to have those features built-in and suspected that a hardware disassembly (to reach the internal flash drive) would be required. Just I'm not ready to try myself ;-)

Thanks anyway!

**Comment by magcode** [comment]
True, its a pity that Lametric does not deliver the features we need.
Unfortunately there is no way at the moment to hack the device without opening it. I struggled a while to do so, but it turned out to be doable.
